[package]
name = "raytracing"
version = "0.2.0"
authors = ["Adam Vandolder <adam.vandolder@gmail.com>"]
edition = "2024"
description = "Simple raytracer based off Ray Tracing in One Weekend"

[dependencies]
image = { version = "0.25", features = ["rayon"] }
clap = { version = "4", features = ["derive"] }
itertools = "0.14"
oidn = "2.3.3"
rand = "0.9"
rayon = "1.11.0"

[profile.dev]
opt-level = 3
